---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
        exclude_types:
          - json
      - id: trailing-whitespace
      - id: no-commit-to-branch
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs
      - id: detect-private-key
  - repo: local
    hooks:
      - id: ruff-check
        name: Run the ruff linter
        entry: ruff check
        types: [python]
        args: [--fix]
        language: unsupported
      - id: ruff-format
        name: Run the ruff formatter
        entry: ruff format
        types: [python]
        language: unsupported
  - repo: local
    hooks:
      - id: super-linter
        name: Super-linter
        # Docker hook mounts the workspace at /src, so we point super-linter there.
        # Note: when super-linter version is bumped here, make sure to upgrade in CI as well.
        entry: >
          --rm --platform linux/amd64
          --env-file .github/super-linter.env
          --env-file .github/super-linter-fix.env
          -e DEFAULT_WORKSPACE=/src
          -e RUN_LOCAL=true
          -e SAVE_SUPER_LINTER_SUMMARY=true
          -e SUPER_LINTER_OUTPUT_DIRECTORY_NAME=.super-linter
          -e SUPER_LINTER_SUMMARY_FILE_NAME=SUMMARY.md
          ghcr.io/super-linter/super-linter@sha256:c95c714f746edc70e54926a69e229c834ffcdec2450bd3475f7865164d749a56
        language: docker_image
        pass_filenames: false
        stages: [pre-push]
  - repo: local
    hooks:
      - id: mypy
        name: Run mypy
        entry: mypy OTCamera tests
        language: unsupported
        types: [python]
        always_run: true
        pass_filenames: false
        args: [--config-file, pyproject.toml]
  - repo: local
    hooks:
      - id: uv-export
        name: Export requirements.txt
        files: '^uv\.lock$'
        language: unsupported
        pass_filenames: false
        entry: uv export
        args:
          [
            "--no-hashes",
            "--no-dev",
            "--extra=pi",
            "--output-file=requirements.txt",
            "--format=requirements-txt",
            "--quiet",
          ]
