---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
        exclude_types:
          - json
      - id: trailing-whitespace
      - id: no-commit-to-branch
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.15
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: Run mypy
        entry: mypy OTCamera tests
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
        args: [--config-file, pyproject.toml]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - -c=./.yamllint.yaml
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/pecigonzalo/pre-commit-shfmt
    rev: v2.2.0
    hooks:
      - id: shell-fmt-docker
        args:
          - -i
          - "2"
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.11.17
    hooks:
      - id: uv-export
        args: [
          "--no-hashes",
          "--extra=pi",
          "--output-file=requirements.txt",
          "--format=requirements-txt",
          "--quiet"
        ]
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.6.1
    hooks:
      - id: editorconfig-checker
        alias: ec
