---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
        exclude_types:
          - json
      - id: trailing-whitespace
      - id: no-commit-to-branch
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs
      - id: detect-private-key
  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args:
          - --profile
          - black
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: mypy
        name: Run mypy
        entry: venv/bin/mypy OTCamera tests
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
        args: [--config-file, pyproject.toml]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - -c=./.yamllint.yaml
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/pecigonzalo/pre-commit-shfmt
    rev: v2.2.0
    hooks:
      - id: shell-fmt-docker
        args:
          - -i
          - "2"
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.6.1
    hooks:
      - id: editorconfig-checker
        alias: ec
