---
site_name: OTCamera API Documentation
theme:
  name: "material"
  palette:
    scheme: slate
  features:
    - navigation.sections
    - toc.integrate
  font: false
  icon:
    logo: octicons/device-camera-video-24
    repo: fontawesome/brands/github

copyright: Copyright &copy; 2021 OpenTrafficCam contributors
repo_url: https://github.com/OpenTrafficCam/OTCamera
repo_name: OpenTrafficCam/OTCamera

nav:
  - index.md
  - Code Reference: reference/

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: date
      timezone: Europe/Berlin
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://installer.readthedocs.io/en/stable/objects.inv # demonstration purpose in the docs
            - https://mkdocstrings.github.io/autorefs/objects.inv
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
            merge_init_into_class: yes
            show_submodules: yes
  - autorefs
