site_name: OTCamera API Documentation

theme:
  name: material
  palette:
    scheme: default
  font: false
  language: en
  logo: assets/OTC_icon_white.svg
  favicon: assets/OTC_icon.svg
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    - navigation.expands
    # - search.suggest
    # - search.highlight
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/color.css
  - stylesheets/fonts.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/opentrafficcam
      name: OpenTrafficCam on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/OpenTrafficCam
      name: OpenTrafficCam on GitHub

copyright: Copyright &copy; 2020 - 2021 OpenTrafficCam Contributors
repo_url: https://github.com/OpenTrafficCam/OTDocs
repo_name: OpenTrafficCam/OTDocs
edit_uri: edit/master/docs/

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  # - meta

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: date
      timezone: Europe/Berlin
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("OTCamera")
