---
debug_mode: false

relay_server: false

recording:
  start_hour: 6
  end_hour: 22
  interval_length: 15
  num_intervals: 0
  min_free_space: 1

camera:
  fps: 20
  resolution:
    width: 1640
    height: 1232
  exposure_mode: nightpreview
  drc_strength: high
  rotation: 180
  awb_mode: greyworld
  meter_mode: average

preview:
  path: ~/OTCamera/webfiles/preview.jpg
  format: jpeg
  interval: 5
  send_to_external: false
  url: http://your-server:8080/projects/0/sites/1/cameras/2/current_frame

#ftp_upload:
#  enable: false
#  host:
#  port: 21
#  user:
#  password:
#  server_source: /

#s3_upload:
#  enable: false
#  access_key:
#  secret_key:
#  bucket:
#  region:
#  endpoint_url:

video:
  dir: ~/videos/
  format: h264
  resolution:
    width: 800
    height: 600
  encoder:
    profile: high
    level: 4
    bitrate: 600000
    quality: 30

wifi:
  delay: 900

hardware:
  pcb_version: v2
  use_leds: false
  use_buttons: false
  use_adc: false

msteams:
  enable: false
  url: null
  max_failed_send_attempts: 2

adc:
  threshold_external_power: 2.5
  threshold_low_battery: 3.3
