---
# Values set to null will use the default config

general:
  debug: true # Turn debug mode on to get additional log entries
  interval: 15 # Interval length in minutes before video splits
  n_intervals: 0 # Number of full intervals to record (0=infinit)
  preview_interval: 5 # Interval between two preview images in seconds
  min_free_space: 1 # Interval between two preview images in seconds
  prefix: null # prefix for video name and annotation. If set to null use hostname
  video_dir: ~/videos/ # Path to save preview
  preview_path: ~/OTCamera/webfiles/preview.jpg # Path to save preview
  template_html_path: ~/OTCamera/webfiles/template.html # Path to template html file
  index_html_path: ~/OTCamera/webfiles/index.html # Path to the index html

camera:
  fps: 20 # Frames per second. 10-20 should be enough
  resolution: [1640, 1232] # Resolution of the camera module works internally. Field of view could be smaller with other values
  exposure_mode: nightpreview # Controls the analog and digital gains
  drc_strength: high # Sets dynamic range compression to lighten dark areas and to darken light areas
  rotation: 180 # Rotate the whole camera image
  awb_mode: greyworld # Controls the auto white balancing mode. `greyworld` is a specific mode for NoIR modules

video:
  format: h264 # Encoding format
  preview_format: jpeg # Filetype of the static preview image
  resize: [800, 800] # Resolution of the saved video file, not the camera itself
  profile: high # Profile used in h264 encoder
  level: "4" # Level used in h264 encoder
  bitrate: 600000 # Bitrate used in h264 encoder
  quality: 30 # Quality used in h264 encoder

hardware:
  use_led: true # True if Status-LEDs are connected
  use_buttons: false # True if hardware buttons are connected
  wifi_delay: 900 # Delay in seconds before WiFi turns off

