name: Move new issues into ToDo-List

on:
  issues:
    types: [labeled]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        if: |
          contains(github.event.issue.labels.*.name, 'bug') ||
          contains(github.event.pull_request.labels.*.name, 'bug')
        with:
          project: ToDo-List
          column: Review in progress
          repo-token: ${{ secrets.TOKEN_SEBASTIAN }}
